//! Wire protocol between `psroot-netshim` (injected in the container) and
//! `psroot-netstack-host` (the runtime-side daemon).
//!
//! # Design goals
//!
//! * **Zero-allocation** on the hot path. All messages are `#[repr(C)]`
//!   fixed-layout POD that can be written directly into a shared-memory
//!   ring slot with a single memcpy.
//! * **Cache-line friendly.** Slot header is 32 bytes; the rest of the
//!   4 KiB slot is pure payload.
//! * **No serde.** serde would require allocation + generics; here we use
//!   raw byte encoding validated by `const` assertions.
//! * **Forward-compatible.** `opcode` is a `u16`; unknown opcodes are
//!   answered with `Status::UnknownOp` rather than disconnecting the
//!   shim. Flag bits and reserved fields give breathing room.
//!
//! # Slot layout (4096 bytes)
//!
//! ```text
//! offset  size  field
//! ─────── ────  ─────────────────────────────────────────
//! 0       2     opcode        (OpCode / StatusCode on reply)
//! 2       2     flags         (FLAG_* bits)
//! 4       4     correlation   (request id, echoed in reply)
//! 8       4     socket_id     (logical socket handle, 0 if n/a)
//! 12      4     payload_len   (bytes valid in `data[]`)
//! 16      16    args          (opcode-specific fixed args)
//! 32      4064  data          (variable-length payload)
//! ```
//!
//! Bytes in `data[]` beyond `payload_len` are undefined.
//! Payloads larger than `DATA_CAPACITY` are fragmented across multiple
//! messages with `FLAG_MORE` set on all but the last fragment.

#![allow(clippy::missing_safety_doc)]

use core::mem::size_of;

/// Total slot size including header. Must be power of two.
pub const SLOT_SIZE: usize = 4096;
/// Bytes per slot reserved for the fixed header (see module doc).
pub const HEADER_SIZE: usize = 32;
/// Bytes available for variable payload inside a single slot.
pub const DATA_CAPACITY: usize = SLOT_SIZE - HEADER_SIZE;

/// Default number of slots in one ring. Configurable at creation time;
/// the constant here is what the container runtime picks by default.
pub const DEFAULT_RING_SLOTS: u32 = 256;

/// Fragmentation bit: more slots follow for the same correlation id.
pub const FLAG_MORE: u16 = 1 << 0;
/// Reply indicates success. Absent = error; check the opcode field
/// (reinterpreted as [`StatusCode`]).
pub const FLAG_REPLY_OK: u16 = 1 << 1;
/// Request was generated by an internal event (not a direct syscall from
/// the app). Currently unused; reserved for peer-initiated messages.
pub const FLAG_EVENT: u16 = 1 << 2;

// ────────────────────────────── opcodes ────────────────────────────────

/// Opcodes sent by the container (`Request`) and replies (`Response`).
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpCode {
    /// Initial handshake. Shim sends its protocol version; host replies
    /// with its version, negotiated virtual IP, and MTU.
    Hello = 0x0001,

    /// Create a new logical socket. Args: `af:u16, typ:u16, proto:u32, flags:u32`.
    /// Returns a `socket_id` in the reply's `socket_id` field.
    Socket = 0x0010,
    /// Bind a socket to a (virtual) address. Data: `SockAddrBytes`.
    Bind = 0x0011,
    /// Connect to a (virtual) peer. Data: `SockAddrBytes`.
    Connect = 0x0012,
    /// Mark a socket as a passive listener. Args: `backlog:u32`.
    Listen = 0x0013,
    /// Accept. Blocks until a new connection is available. Reply's
    /// `socket_id` is the accepted connection; data is the peer address.
    Accept = 0x0014,
    /// Send bytes on a connected socket. Data is the payload.
    Send = 0x0015,
    /// Receive. Args: `max:u32`. Reply data is what was read.
    Recv = 0x0016,
    /// Close. No reply data.
    Close = 0x0017,
    /// Shutdown (0=recv,1=send,2=both). Args: `how:u32`.
    Shutdown = 0x0018,
    /// getsockname — reply data is `SockAddrBytes`.
    GetSockName = 0x0019,
    /// getpeername — reply data is `SockAddrBytes`.
    GetPeerName = 0x001A,
    /// setsockopt — args `level:i32, name:i32`, data is opt value.
    SetSockOpt = 0x001B,
    /// getsockopt — args `level:i32, name:i32`, reply data is opt value.
    GetSockOpt = 0x001C,

    /// Resolve a hostname (GetAddrInfoW equivalent). Data: UTF-8 hostname.
    Resolve = 0x0030,

    /// UDP `sendto`. Payload: `SockAddrBytes` (28 bytes) followed by the
    /// datagram bytes. Reply echoes the number of bytes sent in
    /// `args[0..4]`.
    SendTo = 0x0040,
    /// UDP `recvfrom`. Args: `max:u32`. Reply payload: `SockAddrBytes`
    /// (28 bytes) followed by the datagram bytes.
    RecvFrom = 0x0041,

    /// Goodbye from the shim (container exiting).
    Bye = 0xFFFE,
}

impl OpCode {
    pub fn from_raw(v: u16) -> Option<Self> {
        Some(match v {
            0x0001 => Self::Hello,
            0x0010 => Self::Socket,
            0x0011 => Self::Bind,
            0x0012 => Self::Connect,
            0x0013 => Self::Listen,
            0x0014 => Self::Accept,
            0x0015 => Self::Send,
            0x0016 => Self::Recv,
            0x0017 => Self::Close,
            0x0018 => Self::Shutdown,
            0x0019 => Self::GetSockName,
            0x001A => Self::GetPeerName,
            0x001B => Self::SetSockOpt,
            0x001C => Self::GetSockOpt,
            0x0030 => Self::Resolve,
            0x0040 => Self::SendTo,
            0x0041 => Self::RecvFrom,
            0xFFFE => Self::Bye,
            _ => return None,
        })
    }
}

/// Status codes sent in a reply when `FLAG_REPLY_OK` is NOT set.
/// When the reply is an error, the `opcode` field is interpreted as
/// [`StatusCode`] instead of [`OpCode`].
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StatusCode {
    /// Opcode not recognised.
    UnknownOp = 1,
    /// Socket id not found.
    BadSocket = 2,
    /// Operation would block and socket is non-blocking.
    WouldBlock = 3,
    /// Connection refused by virtual peer / real peer.
    ConnRefused = 4,
    /// Operation not supported in this build / Phase 1.
    NotSupported = 5,
    /// Host system error — refer to `args[0..4]` for Win32 / errno.
    HostError = 6,
    /// Connection reset.
    ConnReset = 7,
    /// Payload too large for a single slot and fragmentation is disabled.
    TooLarge = 8,
    /// Address is already in use.
    AddrInUse = 9,
    /// Address not available.
    AddrNotAvail = 10,
}

// ─────────────────────────── sockaddr encoding ─────────────────────────

/// Address family tag for [`SockAddrBytes`]. Intentionally narrow — we
/// only support IPv4 and IPv6 over the netstack.
pub const AF_INET_V: u16 = 2;
pub const AF_INET6_V: u16 = 23;

/// Compact sockaddr encoding used in message payloads.
///
/// * IPv4 — `family(2) + port(2) + addr(4)` = 8 bytes
/// * IPv6 — `family(2) + port(2) + flow(4) + addr(16) + scope(4)` = 28 bytes
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SockAddrBytes {
    pub family: u16,
    pub port: u16,
    pub v6_flow: u32, // 0 for IPv4
    pub addr: [u8; 16],
    pub v6_scope: u32, // 0 for IPv4
}

impl SockAddrBytes {
    pub const fn zeroed() -> Self {
        Self {
            family: 0,
            port: 0,
            v6_flow: 0,
            addr: [0u8; 16],
            v6_scope: 0,
        }
    }

    pub const fn v4(addr: [u8; 4], port: u16) -> Self {
        let mut s = Self::zeroed();
        s.family = AF_INET_V;
        s.port = port;
        s.addr[0] = addr[0];
        s.addr[1] = addr[1];
        s.addr[2] = addr[2];
        s.addr[3] = addr[3];
        s
    }

    pub const fn v6(addr: [u8; 16], port: u16, flow: u32, scope: u32) -> Self {
        Self {
            family: AF_INET6_V,
            port,
            v6_flow: flow,
            addr,
            v6_scope: scope,
        }
    }
}

// ──────────────────────────── slot header ──────────────────────────────

/// In-memory header of a ring slot.
///
/// `#[repr(C)]` guarantees the layout matches what the shim on the other
/// side of the shared mapping expects. Both sides are built from the same
/// crate so ABI mismatch is impossible.
#[repr(C, align(16))]
#[derive(Debug, Clone, Copy)]
pub struct SlotHeader {
    pub opcode: u16,
    pub flags: u16,
    pub correlation: u32,
    pub socket_id: u32,
    pub payload_len: u32,
    pub args: [u8; 16],
}

impl SlotHeader {
    pub const fn new(opcode: OpCode, correlation: u32) -> Self {
        Self {
            opcode: opcode as u16,
            flags: 0,
            correlation,
            socket_id: 0,
            payload_len: 0,
            args: [0u8; 16],
        }
    }

    pub const fn reply_ok(correlation: u32, socket_id: u32) -> Self {
        Self {
            opcode: 0,
            flags: FLAG_REPLY_OK,
            correlation,
            socket_id,
            payload_len: 0,
            args: [0u8; 16],
        }
    }

    pub const fn reply_err(correlation: u32, status: StatusCode) -> Self {
        Self {
            opcode: status as u16,
            flags: 0,
            correlation,
            socket_id: 0,
            payload_len: 0,
            args: [0u8; 16],
        }
    }

    pub fn is_ok(&self) -> bool {
        self.flags & FLAG_REPLY_OK != 0
    }
}

// Compile-time ABI guards. If these ever trip, EVERY shim built against a
// different psroot version is in trouble, so fail fast at build time.
const _: () = assert!(size_of::<SlotHeader>() == HEADER_SIZE);
const _: () = assert!(size_of::<SockAddrBytes>() == 28);
const _: () = assert!(SLOT_SIZE.is_power_of_two());

// ──────────────────────── argument helpers ─────────────────────────────

/// Pack `(af, typ, proto, flags)` into [`SlotHeader::args`] for OpCode::Socket.
#[inline]
pub fn pack_socket_args(af: u16, typ: u16, proto: u32, flags: u32) -> [u8; 16] {
    let mut a = [0u8; 16];
    a[0..2].copy_from_slice(&af.to_le_bytes());
    a[2..4].copy_from_slice(&typ.to_le_bytes());
    a[4..8].copy_from_slice(&proto.to_le_bytes());
    a[8..12].copy_from_slice(&flags.to_le_bytes());
    a
}

#[inline]
pub fn unpack_socket_args(a: &[u8; 16]) -> (u16, u16, u32, u32) {
    let af = u16::from_le_bytes([a[0], a[1]]);
    let typ = u16::from_le_bytes([a[2], a[3]]);
    let proto = u32::from_le_bytes([a[4], a[5], a[6], a[7]]);
    let flags = u32::from_le_bytes([a[8], a[9], a[10], a[11]]);
    (af, typ, proto, flags)
}

#[inline]
pub fn pack_u32(v: u32) -> [u8; 16] {
    let mut a = [0u8; 16];
    a[0..4].copy_from_slice(&v.to_le_bytes());
    a
}

#[inline]
pub fn unpack_u32(a: &[u8; 16]) -> u32 {
    u32::from_le_bytes([a[0], a[1], a[2], a[3]])
}

// ───────────────────────────── tests ───────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn opcode_roundtrip() {
        for raw in [0x0001, 0x0010, 0x0015, 0x0030, 0xFFFE] {
            let op = OpCode::from_raw(raw).unwrap();
            assert_eq!(op as u16, raw);
        }
        assert!(OpCode::from_raw(0xABCD).is_none());
    }

    #[test]
    fn slot_header_layout() {
        assert_eq!(size_of::<SlotHeader>(), HEADER_SIZE);
        let h = SlotHeader::new(OpCode::Connect, 42);
        assert_eq!(h.correlation, 42);
        assert_eq!(h.opcode, OpCode::Connect as u16);
    }

    #[test]
    fn reply_helpers() {
        let ok = SlotHeader::reply_ok(7, 12);
        assert!(ok.is_ok());
        assert_eq!(ok.correlation, 7);
        assert_eq!(ok.socket_id, 12);

        let err = SlotHeader::reply_err(7, StatusCode::WouldBlock);
        assert!(!err.is_ok());
        assert_eq!(err.opcode, StatusCode::WouldBlock as u16);
    }

    #[test]
    fn sockaddr_v4() {
        let s = SockAddrBytes::v4([10, 88, 0, 2], 8080);
        assert_eq!(s.family, AF_INET_V);
        assert_eq!(s.port, 8080);
        assert_eq!(&s.addr[..4], &[10, 88, 0, 2]);
    }

    #[test]
    fn pack_unpack_socket_args() {
        let a = pack_socket_args(2, 1, 6, 0);
        let (af, typ, proto, flags) = unpack_socket_args(&a);
        assert_eq!((af, typ, proto, flags), (2, 1, 6, 0));
    }

    #[test]
    fn pack_unpack_u32() {
        let a = pack_u32(0xDEADBEEF);
        assert_eq!(unpack_u32(&a), 0xDEADBEEF);
    }
}
